name: maintainers

on:
  pull_request:
    branches:
    - develop
    paths:
      - 'var/spack/repos/builtin/packages/**'

jobs:
  maintainers:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Spack
      uses: actions/checkout@v2
    - name: Get Changed Files
      id: changes
      uses: lots0logs/gh-action-get-changed-files@2.0.6
      with:
        token: GITHUB_TOKEN
    - run: |
        echo ${{ steps.changes.outputs.all }}
        echo ${{ steps.changes.outputs.added }}
        echo ${{ steps.changes.outputs.deleted }}
        echo ${{ steps.changes.outputs.renamed }}
        echo ${{ steps.changes.outputs.modified }}
    - name: Get Maintainers
      id: maintainers
      uses: ./.github/actions/maintainers
      with:
        args: ${{ github.actor }} ${{ steps.changes.outputs.all }}
    - run: |
        echo ${{ steps.maintainers.outputs.packages-with-maintainers }}
        echo ${{ steps.maintainers.outputs.packages-without-maintainers }}
        echo ${{ steps.maintainers.outputs.maintainers }}
