name: maintainers

on:
  pull_request:
    branches:
    - develop
    paths:
      - 'var/spack/repos/builtin/packages/**'

jobs:
  maintainers:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Spack
      uses: actions/checkout@v2
    - name: Get Changed Files
      id: changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ','
    - run: |
        echo ${{ steps.changes.outputs.files }}
        echo ${{ steps.changes.outputs.files_added }}
        echo ${{ steps.changes.outputs.files_modified }}
        echo ${{ steps.changes.outputs.files_removed }}
    - name: Get Maintainers
      id: maintainers
      uses: ./.github/actions/maintainers
      with:
        author: ${{ github.actor }}
        changes: ${{ steps.changes.outputs.files }}
    - run: |
        echo ${{ steps.maintainers.outputs.packages-with-maintainers }}
        echo ${{ steps.maintainers.outputs.packages-without-maintainers }}
        echo ${{ steps.maintainers.outputs.maintainers }}
    - name: Notify Maintainers
      uses: peter-evans/create-or-update-comment@v1.4.1
      with:
        body: |
          ${{ steps.maintainers.outputs.maintainers }} can you review this PR?

          This PR modifies the following package(s), for which you are listed as maintainers:
          ${{ steps.maintainers.outputs.packages-with-maintainers }}
      if: ${{ steps.maintainers.outputs.maintainers }}
    - name: Request Maintainers
      uses: peter-evans/create-or-update-comment@v1.4.1
      with:
        body: |
          Hi ${{ github.actor }}! I noticed that the following package(s) don't have maintainers:
          ${{ steps.maintainers.outputs.packages-without-maintainers }}

          Are you interested in adopting these package(s)? If so, simply add the following to the package class:
          ```python
              maintainers = ['${{ github.actor }}']
          ```
          You don't have to be a Spack expert or package developer in order to be a "maintainer", it just gives us a list of users willing to review PRs or debug issues relating to this package.
      if: ${{ steps.maintainers.outputs.packages-without-maintainers }}
