name: maintainers

on:
  pull_request:
    branches:
    - develop
    paths:
      - 'var/spack/repos/builtin/packages/**'

jobs:
  maintainers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch origin ${{ github.base_ref }}
    #- uses: spack/.github/actions/my-maintainers
    #- run: |
    #    echo ${{ steps.maintainers.outputs.packages-with-maintainers }}
    #    echo ${{ steps.maintainers.outputs.packages-without-maintainers }}
    #    echo ${{ steps.maintainers.outputs.maintainers }}
    #    echo ${{ steps.maintainers.outputs.author }}
