name: maintainers

on:
  pull_request:
    branches:
    - develop
    paths:
      - 'var/spack/repos/builtin/packages/**'

jobs:
  maintainers:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Spack
      uses: actions/checkout@v2
    - name: Get Changed Files
      id: changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ','
    - run: |
        echo ${{ steps.changes.outputs.files }}
        echo ${{ steps.changes.outputs.files_added }}
        echo ${{ steps.changes.outputs.files_modified }}
        echo ${{ steps.changes.outputs.files_removed }}
    - name: Get Maintainers
      id: maintainers
      uses: ./.github/actions/maintainers
      with:
        author: ${{ github.actor }}
        changes: ${{ steps.changes.outputs.files }}
    - run: |
        echo ${{ steps.maintainers.outputs.packages-with-maintainers }}
        echo ${{ steps.maintainers.outputs.packages-without-maintainers }}
        echo ${{ steps.maintainers.outputs.maintainers }}
    - name: Notify Maintainers
      uses: harupy/comment-on-pr@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: notify-maintainers.md
      if: ${{ steps.maintainers.outputs.maintainers }}
    - name: Request Maintainers
      uses: harupy/comment-on-pr@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: request-maintainers.md
      if: ${{ steps.maintainers.outputs.packages-without-maintainers }}
